name: Demo1
on:
    workflow_dispatch:

jobs:
  job1:
    name: Demo1 - Job1
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Composite action
        uses: ./actions/action-with-post-steps